name: 'Next Version'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: Jules-C
  GIT_AUTHOR_EMAIL: julie@fractel.net
  GIT_COMMITTER_NAME: Jules-C
  GIT_COMMITTER_EMAIL: julie@fractel.net
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  next-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.13.1 ]

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Node.js dependencies'
        run: npm ci --legacy-peer-deps

      - name: 'Starting semantic release'
        run: npx semantic-release
